### ISSUE TITLE
Running. the model on in-house data

### ISSUE THREAD

**Issue by Shawnmhy** [jiyuuchc/lacss#2]
Hi, I am wondering if I can run the model on my own data? For the model run, is it required to have both nucleus and cytoplasm staining? Thank you.

**Comment by jiyuuchc** [comment]
Are you trying to run a pretrained-model, or are you trying to train a custom model based on your own data?

For the former, you can download pretrained model weights at https://data.mendeley.com/datasets/sj3vrvm6w3/1 The two pretrained models were optimized for (1) LIVECell and (2) TissueNet datasets. The model will accept any image with 1, 2 or 3 color channels, but the accuracy will be impacted by the amount of domain shift -- how different is your image in comparison to the training images. Check the examples in the inference demo (see project front page) notebook to see how to set it up.

For the latter, you can train model on any type of data you have, as long as you label the locations of every cells. Nucleus images will be very useful if you want to produce cell locations via a program. Otherwise, if you don't have nucleus images, you will most likely mark the cell locations by hand (e.g. using ImageJ). Again, follow the example notebooks to setup your own training pipeline.

Ji
